// Code generated by go-swagger; DO NOT EDIT.

package promotions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
)

// GetPromotionsUsingGET1Reader is a Reader for the GetPromotionsUsingGET1 structure.
type GetPromotionsUsingGET1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPromotionsUsingGET1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPromotionsUsingGET1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetPromotionsUsingGET1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetPromotionsUsingGET1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetPromotionsUsingGET1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPromotionsUsingGET1OK creates a GetPromotionsUsingGET1OK with default headers values
func NewGetPromotionsUsingGET1OK() *GetPromotionsUsingGET1OK {
	return &GetPromotionsUsingGET1OK{}
}

/*GetPromotionsUsingGET1OK handles this case with default header values.

OK
*/
type GetPromotionsUsingGET1OK struct {
	Payload *models.PromotionListWsDTO
}

func (o *GetPromotionsUsingGET1OK) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/promotions][%d] getPromotionsUsingGET1OK  %+v", 200, o.Payload)
}

func (o *GetPromotionsUsingGET1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PromotionListWsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPromotionsUsingGET1Unauthorized creates a GetPromotionsUsingGET1Unauthorized with default headers values
func NewGetPromotionsUsingGET1Unauthorized() *GetPromotionsUsingGET1Unauthorized {
	return &GetPromotionsUsingGET1Unauthorized{}
}

/*GetPromotionsUsingGET1Unauthorized handles this case with default header values.

Unauthorized
*/
type GetPromotionsUsingGET1Unauthorized struct {
}

func (o *GetPromotionsUsingGET1Unauthorized) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/promotions][%d] getPromotionsUsingGET1Unauthorized ", 401)
}

func (o *GetPromotionsUsingGET1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPromotionsUsingGET1Forbidden creates a GetPromotionsUsingGET1Forbidden with default headers values
func NewGetPromotionsUsingGET1Forbidden() *GetPromotionsUsingGET1Forbidden {
	return &GetPromotionsUsingGET1Forbidden{}
}

/*GetPromotionsUsingGET1Forbidden handles this case with default header values.

Forbidden
*/
type GetPromotionsUsingGET1Forbidden struct {
}

func (o *GetPromotionsUsingGET1Forbidden) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/promotions][%d] getPromotionsUsingGET1Forbidden ", 403)
}

func (o *GetPromotionsUsingGET1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPromotionsUsingGET1NotFound creates a GetPromotionsUsingGET1NotFound with default headers values
func NewGetPromotionsUsingGET1NotFound() *GetPromotionsUsingGET1NotFound {
	return &GetPromotionsUsingGET1NotFound{}
}

/*GetPromotionsUsingGET1NotFound handles this case with default header values.

Not Found
*/
type GetPromotionsUsingGET1NotFound struct {
}

func (o *GetPromotionsUsingGET1NotFound) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/promotions][%d] getPromotionsUsingGET1NotFound ", 404)
}

func (o *GetPromotionsUsingGET1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
