apiVersion: eventing.kyma.cx/v1alpha1
kind: Subscription
metadata:
  name: gopdf-order-created
  labels:
    example: something-something
spec:
  endpoint: http://gopdf.mini-stage1:8080/event/order.created
  push_request_timeout_ms: 2000
  max_inflight: 400
  include_subscription_name_header: true
  event_type: order.created
  event_type_version: v1
  source_id: ec-default

---
apiVersion: eventing.kyma.cx/v1alpha1
kind: Subscription
metadata:
  name: gopdf-add-to-card
  labels:
    example: something-something
spec:
  endpoint: http://gopdf.mini-stage1:8080/event/product.addtocart
  push_request_timeout_ms: 2000
  max_inflight: 400
  include_subscription_name_header: true
  event_type: product.addtocart
  event_type_version: v1
  source_id: ec-default

---
apiVersion: eventing.kyma.cx/v1alpha1
kind: Subscription
metadata:
  name: gopdf-order-consignmentprocessing
  labels:
    example: something-something
spec:
  endpoint: http://gopdf.mini-stage1:8080/event/consigment.consignmentprocessing
  push_request_timeout_ms: 2000
  max_inflight: 400
  include_subscription_name_header: true
  event_type: consigment.consignmentprocessing
  event_type_version: v1
  source_id: ec-default

