// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
	"golang.org/x/net/context"
)

// NewCreateReviewUsingPOST1Params creates a new CreateReviewUsingPOST1Params object
// with the default values initialized.
func NewCreateReviewUsingPOST1Params() *CreateReviewUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateReviewUsingPOST1Params{
		Fields: &fieldsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateReviewUsingPOST1ParamsWithTimeout creates a new CreateReviewUsingPOST1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateReviewUsingPOST1ParamsWithTimeout(timeout time.Duration) *CreateReviewUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateReviewUsingPOST1Params{
		Fields: &fieldsDefault,

		timeout: timeout,
	}
}

// NewCreateReviewUsingPOST1ParamsWithContext creates a new CreateReviewUsingPOST1Params object
// with the default values initialized, and the ability to set a context for a request
func NewCreateReviewUsingPOST1ParamsWithContext(ctx context.Context) *CreateReviewUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateReviewUsingPOST1Params{
		Fields: &fieldsDefault,

		Context: ctx,
	}
}

// NewCreateReviewUsingPOST1ParamsWithHTTPClient creates a new CreateReviewUsingPOST1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateReviewUsingPOST1ParamsWithHTTPClient(client *http.Client) *CreateReviewUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateReviewUsingPOST1Params{
		Fields:     &fieldsDefault,
		HTTPClient: client,
	}
}

/*CreateReviewUsingPOST1Params contains all the parameters to send to the API endpoint
for the create review using p o s t 1 operation typically these are written to a http.Request
*/
type CreateReviewUsingPOST1Params struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*Fields
	  Response configuration. This is the list of fields that should be returned in the response body.

	*/
	Fields *string
	/*ProductCode
	  Product identifier

	*/
	ProductCode string
	/*Review
	  Object contains review details like : rating, alias, headline, comment

	*/
	Review *models.ReviewWsDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithTimeout(timeout time.Duration) *CreateReviewUsingPOST1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithContext(ctx context.Context) *CreateReviewUsingPOST1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithHTTPClient(client *http.Client) *CreateReviewUsingPOST1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithBaseSiteID(baseSiteID string) *CreateReviewUsingPOST1Params {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithFields adds the fields to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithFields(fields *string) *CreateReviewUsingPOST1Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithProductCode adds the productCode to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithProductCode(productCode string) *CreateReviewUsingPOST1Params {
	o.SetProductCode(productCode)
	return o
}

// SetProductCode adds the productCode to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetProductCode(productCode string) {
	o.ProductCode = productCode
}

// WithReview adds the review to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) WithReview(review *models.ReviewWsDTO) *CreateReviewUsingPOST1Params {
	o.SetReview(review)
	return o
}

// SetReview adds the review to the create review using p o s t 1 params
func (o *CreateReviewUsingPOST1Params) SetReview(review *models.ReviewWsDTO) {
	o.Review = review
}

// WriteToRequest writes these params to a swagger request
func (o *CreateReviewUsingPOST1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param productCode
	if err := r.SetPathParam("productCode", o.ProductCode); err != nil {
		return err
	}

	if o.Review != nil {
		if err := r.SetBodyParam(o.Review); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
