// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
)

// ExportProductReferencesUsingGETReader is a Reader for the ExportProductReferencesUsingGET structure.
type ExportProductReferencesUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportProductReferencesUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExportProductReferencesUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewExportProductReferencesUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewExportProductReferencesUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewExportProductReferencesUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExportProductReferencesUsingGETOK creates a ExportProductReferencesUsingGETOK with default headers values
func NewExportProductReferencesUsingGETOK() *ExportProductReferencesUsingGETOK {
	return &ExportProductReferencesUsingGETOK{}
}

/*ExportProductReferencesUsingGETOK handles this case with default header values.

OK
*/
type ExportProductReferencesUsingGETOK struct {
	Payload *models.ProductReferenceListWsDTO
}

func (o *ExportProductReferencesUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/references][%d] exportProductReferencesUsingGETOK  %+v", 200, o.Payload)
}

func (o *ExportProductReferencesUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductReferenceListWsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportProductReferencesUsingGETUnauthorized creates a ExportProductReferencesUsingGETUnauthorized with default headers values
func NewExportProductReferencesUsingGETUnauthorized() *ExportProductReferencesUsingGETUnauthorized {
	return &ExportProductReferencesUsingGETUnauthorized{}
}

/*ExportProductReferencesUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type ExportProductReferencesUsingGETUnauthorized struct {
}

func (o *ExportProductReferencesUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/references][%d] exportProductReferencesUsingGETUnauthorized ", 401)
}

func (o *ExportProductReferencesUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportProductReferencesUsingGETForbidden creates a ExportProductReferencesUsingGETForbidden with default headers values
func NewExportProductReferencesUsingGETForbidden() *ExportProductReferencesUsingGETForbidden {
	return &ExportProductReferencesUsingGETForbidden{}
}

/*ExportProductReferencesUsingGETForbidden handles this case with default header values.

Forbidden
*/
type ExportProductReferencesUsingGETForbidden struct {
}

func (o *ExportProductReferencesUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/references][%d] exportProductReferencesUsingGETForbidden ", 403)
}

func (o *ExportProductReferencesUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportProductReferencesUsingGETNotFound creates a ExportProductReferencesUsingGETNotFound with default headers values
func NewExportProductReferencesUsingGETNotFound() *ExportProductReferencesUsingGETNotFound {
	return &ExportProductReferencesUsingGETNotFound{}
}

/*ExportProductReferencesUsingGETNotFound handles this case with default header values.

Not Found
*/
type ExportProductReferencesUsingGETNotFound struct {
}

func (o *ExportProductReferencesUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/references][%d] exportProductReferencesUsingGETNotFound ", 404)
}

func (o *ExportProductReferencesUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
