// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
)

// GetProductReviewsUsingGETReader is a Reader for the GetProductReviewsUsingGET structure.
type GetProductReviewsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductReviewsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProductReviewsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetProductReviewsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetProductReviewsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetProductReviewsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProductReviewsUsingGETOK creates a GetProductReviewsUsingGETOK with default headers values
func NewGetProductReviewsUsingGETOK() *GetProductReviewsUsingGETOK {
	return &GetProductReviewsUsingGETOK{}
}

/*GetProductReviewsUsingGETOK handles this case with default header values.

OK
*/
type GetProductReviewsUsingGETOK struct {
	Payload *models.ReviewListWsDTO
}

func (o *GetProductReviewsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/reviews][%d] getProductReviewsUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetProductReviewsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReviewListWsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductReviewsUsingGETUnauthorized creates a GetProductReviewsUsingGETUnauthorized with default headers values
func NewGetProductReviewsUsingGETUnauthorized() *GetProductReviewsUsingGETUnauthorized {
	return &GetProductReviewsUsingGETUnauthorized{}
}

/*GetProductReviewsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetProductReviewsUsingGETUnauthorized struct {
}

func (o *GetProductReviewsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/reviews][%d] getProductReviewsUsingGETUnauthorized ", 401)
}

func (o *GetProductReviewsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProductReviewsUsingGETForbidden creates a GetProductReviewsUsingGETForbidden with default headers values
func NewGetProductReviewsUsingGETForbidden() *GetProductReviewsUsingGETForbidden {
	return &GetProductReviewsUsingGETForbidden{}
}

/*GetProductReviewsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetProductReviewsUsingGETForbidden struct {
}

func (o *GetProductReviewsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/reviews][%d] getProductReviewsUsingGETForbidden ", 403)
}

func (o *GetProductReviewsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProductReviewsUsingGETNotFound creates a GetProductReviewsUsingGETNotFound with default headers values
func NewGetProductReviewsUsingGETNotFound() *GetProductReviewsUsingGETNotFound {
	return &GetProductReviewsUsingGETNotFound{}
}

/*GetProductReviewsUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetProductReviewsUsingGETNotFound struct {
}

func (o *GetProductReviewsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/reviews][%d] getProductReviewsUsingGETNotFound ", 404)
}

func (o *GetProductReviewsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
