// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
)

// SearchProductStockByLocationUsingGETReader is a Reader for the SearchProductStockByLocationUsingGET structure.
type SearchProductStockByLocationUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchProductStockByLocationUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchProductStockByLocationUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewSearchProductStockByLocationUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewSearchProductStockByLocationUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewSearchProductStockByLocationUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchProductStockByLocationUsingGETOK creates a SearchProductStockByLocationUsingGETOK with default headers values
func NewSearchProductStockByLocationUsingGETOK() *SearchProductStockByLocationUsingGETOK {
	return &SearchProductStockByLocationUsingGETOK{}
}

/*SearchProductStockByLocationUsingGETOK handles this case with default header values.

OK
*/
type SearchProductStockByLocationUsingGETOK struct {
	Payload *models.StoreFinderStockSearchPageWsDTO
}

func (o *SearchProductStockByLocationUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/stock][%d] searchProductStockByLocationUsingGETOK  %+v", 200, o.Payload)
}

func (o *SearchProductStockByLocationUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StoreFinderStockSearchPageWsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchProductStockByLocationUsingGETUnauthorized creates a SearchProductStockByLocationUsingGETUnauthorized with default headers values
func NewSearchProductStockByLocationUsingGETUnauthorized() *SearchProductStockByLocationUsingGETUnauthorized {
	return &SearchProductStockByLocationUsingGETUnauthorized{}
}

/*SearchProductStockByLocationUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type SearchProductStockByLocationUsingGETUnauthorized struct {
}

func (o *SearchProductStockByLocationUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/stock][%d] searchProductStockByLocationUsingGETUnauthorized ", 401)
}

func (o *SearchProductStockByLocationUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchProductStockByLocationUsingGETForbidden creates a SearchProductStockByLocationUsingGETForbidden with default headers values
func NewSearchProductStockByLocationUsingGETForbidden() *SearchProductStockByLocationUsingGETForbidden {
	return &SearchProductStockByLocationUsingGETForbidden{}
}

/*SearchProductStockByLocationUsingGETForbidden handles this case with default header values.

Forbidden
*/
type SearchProductStockByLocationUsingGETForbidden struct {
}

func (o *SearchProductStockByLocationUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/stock][%d] searchProductStockByLocationUsingGETForbidden ", 403)
}

func (o *SearchProductStockByLocationUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchProductStockByLocationUsingGETNotFound creates a SearchProductStockByLocationUsingGETNotFound with default headers values
func NewSearchProductStockByLocationUsingGETNotFound() *SearchProductStockByLocationUsingGETNotFound {
	return &SearchProductStockByLocationUsingGETNotFound{}
}

/*SearchProductStockByLocationUsingGETNotFound handles this case with default header values.

Not Found
*/
type SearchProductStockByLocationUsingGETNotFound struct {
}

func (o *SearchProductStockByLocationUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/products/{productCode}/stock][%d] searchProductStockByLocationUsingGETNotFound ", 404)
}

func (o *SearchProductStockByLocationUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
