// Code generated by go-swagger; DO NOT EDIT.

package countries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetCountriesUsingGETParams creates a new GetCountriesUsingGETParams object
// with the default values initialized.
func NewGetCountriesUsingGETParams() *GetCountriesUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCountriesUsingGETParams{
		Fields: &fieldsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCountriesUsingGETParamsWithTimeout creates a new GetCountriesUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCountriesUsingGETParamsWithTimeout(timeout time.Duration) *GetCountriesUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCountriesUsingGETParams{
		Fields: &fieldsDefault,

		timeout: timeout,
	}
}

// NewGetCountriesUsingGETParamsWithContext creates a new GetCountriesUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCountriesUsingGETParamsWithContext(ctx context.Context) *GetCountriesUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCountriesUsingGETParams{
		Fields: &fieldsDefault,

		Context: ctx,
	}
}

// NewGetCountriesUsingGETParamsWithHTTPClient creates a new GetCountriesUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCountriesUsingGETParamsWithHTTPClient(client *http.Client) *GetCountriesUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCountriesUsingGETParams{
		Fields:     &fieldsDefault,
		HTTPClient: client,
	}
}

/*GetCountriesUsingGETParams contains all the parameters to send to the API endpoint
for the get countries using g e t operation typically these are written to a http.Request
*/
type GetCountriesUsingGETParams struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*Fields
	  Response configuration. This is the list of fields that should be returned in the response body.

	*/
	Fields *string
	/*Type
	  The type of countries.

	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get countries using g e t params
func (o *GetCountriesUsingGETParams) WithTimeout(timeout time.Duration) *GetCountriesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get countries using g e t params
func (o *GetCountriesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get countries using g e t params
func (o *GetCountriesUsingGETParams) WithContext(ctx context.Context) *GetCountriesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get countries using g e t params
func (o *GetCountriesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get countries using g e t params
func (o *GetCountriesUsingGETParams) WithHTTPClient(client *http.Client) *GetCountriesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get countries using g e t params
func (o *GetCountriesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the get countries using g e t params
func (o *GetCountriesUsingGETParams) WithBaseSiteID(baseSiteID string) *GetCountriesUsingGETParams {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the get countries using g e t params
func (o *GetCountriesUsingGETParams) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithFields adds the fields to the get countries using g e t params
func (o *GetCountriesUsingGETParams) WithFields(fields *string) *GetCountriesUsingGETParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get countries using g e t params
func (o *GetCountriesUsingGETParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithType adds the typeVar to the get countries using g e t params
func (o *GetCountriesUsingGETParams) WithType(typeVar *string) *GetCountriesUsingGETParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get countries using g e t params
func (o *GetCountriesUsingGETParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetCountriesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
