// Code generated by go-swagger; DO NOT EDIT.

package base_stores

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new base stores API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for base stores API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetBaseStoreUsingGET gets a base store

Returns details of a specific base store based on its identifier. The response contains detailed base store information.
*/
func (a *Client) GetBaseStoreUsingGET(params *GetBaseStoreUsingGETParams, authInfo runtime.ClientAuthInfoWriter) (*GetBaseStoreUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBaseStoreUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getBaseStoreUsingGET",
		Method:             "GET",
		PathPattern:        "/{baseSiteId}/basestores/{baseStoreUid}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBaseStoreUsingGETReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetBaseStoreUsingGETOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
