// Code generated by go-swagger; DO NOT EDIT.

package base_stores

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetBaseStoreUsingGETParams creates a new GetBaseStoreUsingGETParams object
// with the default values initialized.
func NewGetBaseStoreUsingGETParams() *GetBaseStoreUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetBaseStoreUsingGETParams{
		Fields: &fieldsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBaseStoreUsingGETParamsWithTimeout creates a new GetBaseStoreUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBaseStoreUsingGETParamsWithTimeout(timeout time.Duration) *GetBaseStoreUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetBaseStoreUsingGETParams{
		Fields: &fieldsDefault,

		timeout: timeout,
	}
}

// NewGetBaseStoreUsingGETParamsWithContext creates a new GetBaseStoreUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBaseStoreUsingGETParamsWithContext(ctx context.Context) *GetBaseStoreUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetBaseStoreUsingGETParams{
		Fields: &fieldsDefault,

		Context: ctx,
	}
}

// NewGetBaseStoreUsingGETParamsWithHTTPClient creates a new GetBaseStoreUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBaseStoreUsingGETParamsWithHTTPClient(client *http.Client) *GetBaseStoreUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetBaseStoreUsingGETParams{
		Fields:     &fieldsDefault,
		HTTPClient: client,
	}
}

/*GetBaseStoreUsingGETParams contains all the parameters to send to the API endpoint
for the get base store using g e t operation typically these are written to a http.Request
*/
type GetBaseStoreUsingGETParams struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*BaseStoreUID
	  Base store name

	*/
	BaseStoreUID string
	/*Fields
	  Response configuration. This is the list of fields that should be returned in the response body.

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) WithTimeout(timeout time.Duration) *GetBaseStoreUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) WithContext(ctx context.Context) *GetBaseStoreUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) WithHTTPClient(client *http.Client) *GetBaseStoreUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) WithBaseSiteID(baseSiteID string) *GetBaseStoreUsingGETParams {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithBaseStoreUID adds the baseStoreUID to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) WithBaseStoreUID(baseStoreUID string) *GetBaseStoreUsingGETParams {
	o.SetBaseStoreUID(baseStoreUID)
	return o
}

// SetBaseStoreUID adds the baseStoreUid to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) SetBaseStoreUID(baseStoreUID string) {
	o.BaseStoreUID = baseStoreUID
}

// WithFields adds the fields to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) WithFields(fields *string) *GetBaseStoreUsingGETParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get base store using g e t params
func (o *GetBaseStoreUsingGETParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetBaseStoreUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	// path param baseStoreUid
	if err := r.SetPathParam("baseStoreUid", o.BaseStoreUID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
