// Code generated by go-swagger; DO NOT EDIT.

package extended_carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSopPaymentResponseUsingDELETEReader is a Reader for the DeleteSopPaymentResponseUsingDELETE structure.
type DeleteSopPaymentResponseUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSopPaymentResponseUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSopPaymentResponseUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteSopPaymentResponseUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteSopPaymentResponseUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteSopPaymentResponseUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSopPaymentResponseUsingDELETEOK creates a DeleteSopPaymentResponseUsingDELETEOK with default headers values
func NewDeleteSopPaymentResponseUsingDELETEOK() *DeleteSopPaymentResponseUsingDELETEOK {
	return &DeleteSopPaymentResponseUsingDELETEOK{}
}

/*DeleteSopPaymentResponseUsingDELETEOK handles this case with default header values.

OK
*/
type DeleteSopPaymentResponseUsingDELETEOK struct {
}

func (o *DeleteSopPaymentResponseUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/carts/{cartId}/payment/sop/response][%d] deleteSopPaymentResponseUsingDELETEOK ", 200)
}

func (o *DeleteSopPaymentResponseUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSopPaymentResponseUsingDELETENoContent creates a DeleteSopPaymentResponseUsingDELETENoContent with default headers values
func NewDeleteSopPaymentResponseUsingDELETENoContent() *DeleteSopPaymentResponseUsingDELETENoContent {
	return &DeleteSopPaymentResponseUsingDELETENoContent{}
}

/*DeleteSopPaymentResponseUsingDELETENoContent handles this case with default header values.

No Content
*/
type DeleteSopPaymentResponseUsingDELETENoContent struct {
}

func (o *DeleteSopPaymentResponseUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/carts/{cartId}/payment/sop/response][%d] deleteSopPaymentResponseUsingDELETENoContent ", 204)
}

func (o *DeleteSopPaymentResponseUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSopPaymentResponseUsingDELETEUnauthorized creates a DeleteSopPaymentResponseUsingDELETEUnauthorized with default headers values
func NewDeleteSopPaymentResponseUsingDELETEUnauthorized() *DeleteSopPaymentResponseUsingDELETEUnauthorized {
	return &DeleteSopPaymentResponseUsingDELETEUnauthorized{}
}

/*DeleteSopPaymentResponseUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteSopPaymentResponseUsingDELETEUnauthorized struct {
}

func (o *DeleteSopPaymentResponseUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/carts/{cartId}/payment/sop/response][%d] deleteSopPaymentResponseUsingDELETEUnauthorized ", 401)
}

func (o *DeleteSopPaymentResponseUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSopPaymentResponseUsingDELETEForbidden creates a DeleteSopPaymentResponseUsingDELETEForbidden with default headers values
func NewDeleteSopPaymentResponseUsingDELETEForbidden() *DeleteSopPaymentResponseUsingDELETEForbidden {
	return &DeleteSopPaymentResponseUsingDELETEForbidden{}
}

/*DeleteSopPaymentResponseUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type DeleteSopPaymentResponseUsingDELETEForbidden struct {
}

func (o *DeleteSopPaymentResponseUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/carts/{cartId}/payment/sop/response][%d] deleteSopPaymentResponseUsingDELETEForbidden ", 403)
}

func (o *DeleteSopPaymentResponseUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
