// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
	"golang.org/x/net/context"
)

// NewPutUserUsingPUT1Params creates a new PutUserUsingPUT1Params object
// with the default values initialized.
func NewPutUserUsingPUT1Params() *PutUserUsingPUT1Params {
	var ()
	return &PutUserUsingPUT1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutUserUsingPUT1ParamsWithTimeout creates a new PutUserUsingPUT1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutUserUsingPUT1ParamsWithTimeout(timeout time.Duration) *PutUserUsingPUT1Params {
	var ()
	return &PutUserUsingPUT1Params{

		timeout: timeout,
	}
}

// NewPutUserUsingPUT1ParamsWithContext creates a new PutUserUsingPUT1Params object
// with the default values initialized, and the ability to set a context for a request
func NewPutUserUsingPUT1ParamsWithContext(ctx context.Context) *PutUserUsingPUT1Params {
	var ()
	return &PutUserUsingPUT1Params{

		Context: ctx,
	}
}

// NewPutUserUsingPUT1ParamsWithHTTPClient creates a new PutUserUsingPUT1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutUserUsingPUT1ParamsWithHTTPClient(client *http.Client) *PutUserUsingPUT1Params {
	var ()
	return &PutUserUsingPUT1Params{
		HTTPClient: client,
	}
}

/*PutUserUsingPUT1Params contains all the parameters to send to the API endpoint
for the put user using p u t 1 operation typically these are written to a http.Request
*/
type PutUserUsingPUT1Params struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*User
	  User's object

	*/
	User *models.UserWsDTO
	/*UserID
	  User identifier or one of the literals : 'current' for currently authenticated user, 'anonymous' for anonymous user

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) WithTimeout(timeout time.Duration) *PutUserUsingPUT1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) WithContext(ctx context.Context) *PutUserUsingPUT1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) WithHTTPClient(client *http.Client) *PutUserUsingPUT1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) WithBaseSiteID(baseSiteID string) *PutUserUsingPUT1Params {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithUser adds the user to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) WithUser(user *models.UserWsDTO) *PutUserUsingPUT1Params {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) SetUser(user *models.UserWsDTO) {
	o.User = user
}

// WithUserID adds the userID to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) WithUserID(userID string) *PutUserUsingPUT1Params {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the put user using p u t 1 params
func (o *PutUserUsingPUT1Params) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *PutUserUsingPUT1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
