// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new feeds API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for feeds API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
OrderStatusFeedUsingGET gets a list of orders with status updates

Returns the orders that have changed status. Returns only the elements from the current baseSite that have been updated after the provided timestamp.
*/
func (a *Client) OrderStatusFeedUsingGET(params *OrderStatusFeedUsingGETParams, authInfo runtime.ClientAuthInfoWriter) (*OrderStatusFeedUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrderStatusFeedUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "orderStatusFeedUsingGET",
		Method:             "GET",
		PathPattern:        "/{baseSiteId}/feeds/orders/statusfeed",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrderStatusFeedUsingGETReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OrderStatusFeedUsingGETOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
