// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
)

// CreateAndSetAddressUsingPOST1Reader is a Reader for the CreateAndSetAddressUsingPOST1 structure.
type CreateAndSetAddressUsingPOST1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAndSetAddressUsingPOST1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateAndSetAddressUsingPOST1Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewCreateAndSetAddressUsingPOST1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateAndSetAddressUsingPOST1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateAndSetAddressUsingPOST1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAndSetAddressUsingPOST1Created creates a CreateAndSetAddressUsingPOST1Created with default headers values
func NewCreateAndSetAddressUsingPOST1Created() *CreateAndSetAddressUsingPOST1Created {
	return &CreateAndSetAddressUsingPOST1Created{}
}

/*CreateAndSetAddressUsingPOST1Created handles this case with default header values.

Created
*/
type CreateAndSetAddressUsingPOST1Created struct {
	Payload *models.AddressWsDTO
}

func (o *CreateAndSetAddressUsingPOST1Created) Error() string {
	return fmt.Sprintf("[POST /{baseSiteId}/users/{userId}/carts/{cartId}/addresses/delivery][%d] createAndSetAddressUsingPOST1Created  %+v", 201, o.Payload)
}

func (o *CreateAndSetAddressUsingPOST1Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddressWsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAndSetAddressUsingPOST1Unauthorized creates a CreateAndSetAddressUsingPOST1Unauthorized with default headers values
func NewCreateAndSetAddressUsingPOST1Unauthorized() *CreateAndSetAddressUsingPOST1Unauthorized {
	return &CreateAndSetAddressUsingPOST1Unauthorized{}
}

/*CreateAndSetAddressUsingPOST1Unauthorized handles this case with default header values.

Unauthorized
*/
type CreateAndSetAddressUsingPOST1Unauthorized struct {
}

func (o *CreateAndSetAddressUsingPOST1Unauthorized) Error() string {
	return fmt.Sprintf("[POST /{baseSiteId}/users/{userId}/carts/{cartId}/addresses/delivery][%d] createAndSetAddressUsingPOST1Unauthorized ", 401)
}

func (o *CreateAndSetAddressUsingPOST1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAndSetAddressUsingPOST1Forbidden creates a CreateAndSetAddressUsingPOST1Forbidden with default headers values
func NewCreateAndSetAddressUsingPOST1Forbidden() *CreateAndSetAddressUsingPOST1Forbidden {
	return &CreateAndSetAddressUsingPOST1Forbidden{}
}

/*CreateAndSetAddressUsingPOST1Forbidden handles this case with default header values.

Forbidden
*/
type CreateAndSetAddressUsingPOST1Forbidden struct {
}

func (o *CreateAndSetAddressUsingPOST1Forbidden) Error() string {
	return fmt.Sprintf("[POST /{baseSiteId}/users/{userId}/carts/{cartId}/addresses/delivery][%d] createAndSetAddressUsingPOST1Forbidden ", 403)
}

func (o *CreateAndSetAddressUsingPOST1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAndSetAddressUsingPOST1NotFound creates a CreateAndSetAddressUsingPOST1NotFound with default headers values
func NewCreateAndSetAddressUsingPOST1NotFound() *CreateAndSetAddressUsingPOST1NotFound {
	return &CreateAndSetAddressUsingPOST1NotFound{}
}

/*CreateAndSetAddressUsingPOST1NotFound handles this case with default header values.

Not Found
*/
type CreateAndSetAddressUsingPOST1NotFound struct {
}

func (o *CreateAndSetAddressUsingPOST1NotFound) Error() string {
	return fmt.Sprintf("[POST /{baseSiteId}/users/{userId}/carts/{cartId}/addresses/delivery][%d] createAndSetAddressUsingPOST1NotFound ", 404)
}

func (o *CreateAndSetAddressUsingPOST1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
