// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetCartDeliveryModeUsingGETParams creates a new GetCartDeliveryModeUsingGETParams object
// with the default values initialized.
func NewGetCartDeliveryModeUsingGETParams() *GetCartDeliveryModeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCartDeliveryModeUsingGETParams{
		Fields: &fieldsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCartDeliveryModeUsingGETParamsWithTimeout creates a new GetCartDeliveryModeUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCartDeliveryModeUsingGETParamsWithTimeout(timeout time.Duration) *GetCartDeliveryModeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCartDeliveryModeUsingGETParams{
		Fields: &fieldsDefault,

		timeout: timeout,
	}
}

// NewGetCartDeliveryModeUsingGETParamsWithContext creates a new GetCartDeliveryModeUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCartDeliveryModeUsingGETParamsWithContext(ctx context.Context) *GetCartDeliveryModeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCartDeliveryModeUsingGETParams{
		Fields: &fieldsDefault,

		Context: ctx,
	}
}

// NewGetCartDeliveryModeUsingGETParamsWithHTTPClient creates a new GetCartDeliveryModeUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCartDeliveryModeUsingGETParamsWithHTTPClient(client *http.Client) *GetCartDeliveryModeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetCartDeliveryModeUsingGETParams{
		Fields:     &fieldsDefault,
		HTTPClient: client,
	}
}

/*GetCartDeliveryModeUsingGETParams contains all the parameters to send to the API endpoint
for the get cart delivery mode using g e t operation typically these are written to a http.Request
*/
type GetCartDeliveryModeUsingGETParams struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*CartID
	  Cart identifier: cart code for logged in user, cart guid for anonymous user, 'current' for the last modified cart

	*/
	CartID string
	/*Fields
	  Response configuration. This is the list of fields that should be returned in the response body.

	*/
	Fields *string
	/*UserID
	  User identifier or one of the literals : 'current' for currently authenticated user, 'anonymous' for anonymous user

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithTimeout(timeout time.Duration) *GetCartDeliveryModeUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithContext(ctx context.Context) *GetCartDeliveryModeUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithHTTPClient(client *http.Client) *GetCartDeliveryModeUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithBaseSiteID(baseSiteID string) *GetCartDeliveryModeUsingGETParams {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithCartID adds the cartID to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithCartID(cartID string) *GetCartDeliveryModeUsingGETParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetCartID(cartID string) {
	o.CartID = cartID
}

// WithFields adds the fields to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithFields(fields *string) *GetCartDeliveryModeUsingGETParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserID adds the userID to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) WithUserID(userID string) *GetCartDeliveryModeUsingGETParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get cart delivery mode using g e t params
func (o *GetCartDeliveryModeUsingGETParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCartDeliveryModeUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	// path param cartId
	if err := r.SetPathParam("cartId", o.CartID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
