// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
)

// GetPromotionsUsingGETReader is a Reader for the GetPromotionsUsingGET structure.
type GetPromotionsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPromotionsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPromotionsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetPromotionsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetPromotionsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetPromotionsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPromotionsUsingGETOK creates a GetPromotionsUsingGETOK with default headers values
func NewGetPromotionsUsingGETOK() *GetPromotionsUsingGETOK {
	return &GetPromotionsUsingGETOK{}
}

/*GetPromotionsUsingGETOK handles this case with default header values.

OK
*/
type GetPromotionsUsingGETOK struct {
	Payload *models.PromotionResultListWsDTO
}

func (o *GetPromotionsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/users/{userId}/carts/{cartId}/promotions][%d] getPromotionsUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetPromotionsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PromotionResultListWsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPromotionsUsingGETUnauthorized creates a GetPromotionsUsingGETUnauthorized with default headers values
func NewGetPromotionsUsingGETUnauthorized() *GetPromotionsUsingGETUnauthorized {
	return &GetPromotionsUsingGETUnauthorized{}
}

/*GetPromotionsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetPromotionsUsingGETUnauthorized struct {
}

func (o *GetPromotionsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/users/{userId}/carts/{cartId}/promotions][%d] getPromotionsUsingGETUnauthorized ", 401)
}

func (o *GetPromotionsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPromotionsUsingGETForbidden creates a GetPromotionsUsingGETForbidden with default headers values
func NewGetPromotionsUsingGETForbidden() *GetPromotionsUsingGETForbidden {
	return &GetPromotionsUsingGETForbidden{}
}

/*GetPromotionsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetPromotionsUsingGETForbidden struct {
}

func (o *GetPromotionsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/users/{userId}/carts/{cartId}/promotions][%d] getPromotionsUsingGETForbidden ", 403)
}

func (o *GetPromotionsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPromotionsUsingGETNotFound creates a GetPromotionsUsingGETNotFound with default headers values
func NewGetPromotionsUsingGETNotFound() *GetPromotionsUsingGETNotFound {
	return &GetPromotionsUsingGETNotFound{}
}

/*GetPromotionsUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetPromotionsUsingGETNotFound struct {
}

func (o *GetPromotionsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /{baseSiteId}/users/{userId}/carts/{cartId}/promotions][%d] getPromotionsUsingGETNotFound ", 404)
}

func (o *GetPromotionsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
