// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// SetPaymentDetailsUsingPUTReader is a Reader for the SetPaymentDetailsUsingPUT structure.
type SetPaymentDetailsUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPaymentDetailsUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetPaymentDetailsUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewSetPaymentDetailsUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewSetPaymentDetailsUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewSetPaymentDetailsUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewSetPaymentDetailsUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPaymentDetailsUsingPUTOK creates a SetPaymentDetailsUsingPUTOK with default headers values
func NewSetPaymentDetailsUsingPUTOK() *SetPaymentDetailsUsingPUTOK {
	return &SetPaymentDetailsUsingPUTOK{}
}

/*SetPaymentDetailsUsingPUTOK handles this case with default header values.

OK
*/
type SetPaymentDetailsUsingPUTOK struct {
}

func (o *SetPaymentDetailsUsingPUTOK) Error() string {
	return fmt.Sprintf("[PUT /{baseSiteId}/users/{userId}/carts/{cartId}/paymentdetails][%d] setPaymentDetailsUsingPUTOK ", 200)
}

func (o *SetPaymentDetailsUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetPaymentDetailsUsingPUTCreated creates a SetPaymentDetailsUsingPUTCreated with default headers values
func NewSetPaymentDetailsUsingPUTCreated() *SetPaymentDetailsUsingPUTCreated {
	return &SetPaymentDetailsUsingPUTCreated{}
}

/*SetPaymentDetailsUsingPUTCreated handles this case with default header values.

Created
*/
type SetPaymentDetailsUsingPUTCreated struct {
}

func (o *SetPaymentDetailsUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /{baseSiteId}/users/{userId}/carts/{cartId}/paymentdetails][%d] setPaymentDetailsUsingPUTCreated ", 201)
}

func (o *SetPaymentDetailsUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetPaymentDetailsUsingPUTUnauthorized creates a SetPaymentDetailsUsingPUTUnauthorized with default headers values
func NewSetPaymentDetailsUsingPUTUnauthorized() *SetPaymentDetailsUsingPUTUnauthorized {
	return &SetPaymentDetailsUsingPUTUnauthorized{}
}

/*SetPaymentDetailsUsingPUTUnauthorized handles this case with default header values.

Unauthorized
*/
type SetPaymentDetailsUsingPUTUnauthorized struct {
}

func (o *SetPaymentDetailsUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /{baseSiteId}/users/{userId}/carts/{cartId}/paymentdetails][%d] setPaymentDetailsUsingPUTUnauthorized ", 401)
}

func (o *SetPaymentDetailsUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetPaymentDetailsUsingPUTForbidden creates a SetPaymentDetailsUsingPUTForbidden with default headers values
func NewSetPaymentDetailsUsingPUTForbidden() *SetPaymentDetailsUsingPUTForbidden {
	return &SetPaymentDetailsUsingPUTForbidden{}
}

/*SetPaymentDetailsUsingPUTForbidden handles this case with default header values.

Forbidden
*/
type SetPaymentDetailsUsingPUTForbidden struct {
}

func (o *SetPaymentDetailsUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /{baseSiteId}/users/{userId}/carts/{cartId}/paymentdetails][%d] setPaymentDetailsUsingPUTForbidden ", 403)
}

func (o *SetPaymentDetailsUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetPaymentDetailsUsingPUTNotFound creates a SetPaymentDetailsUsingPUTNotFound with default headers values
func NewSetPaymentDetailsUsingPUTNotFound() *SetPaymentDetailsUsingPUTNotFound {
	return &SetPaymentDetailsUsingPUTNotFound{}
}

/*SetPaymentDetailsUsingPUTNotFound handles this case with default header values.

Not Found
*/
type SetPaymentDetailsUsingPUTNotFound struct {
}

func (o *SetPaymentDetailsUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /{baseSiteId}/users/{userId}/carts/{cartId}/paymentdetails][%d] setPaymentDetailsUsingPUTNotFound ", 404)
}

func (o *SetPaymentDetailsUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
