// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetCountOrdersForUserUsingHEADParams creates a new GetCountOrdersForUserUsingHEADParams object
// with the default values initialized.
func NewGetCountOrdersForUserUsingHEADParams() *GetCountOrdersForUserUsingHEADParams {
	var ()
	return &GetCountOrdersForUserUsingHEADParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCountOrdersForUserUsingHEADParamsWithTimeout creates a new GetCountOrdersForUserUsingHEADParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCountOrdersForUserUsingHEADParamsWithTimeout(timeout time.Duration) *GetCountOrdersForUserUsingHEADParams {
	var ()
	return &GetCountOrdersForUserUsingHEADParams{

		timeout: timeout,
	}
}

// NewGetCountOrdersForUserUsingHEADParamsWithContext creates a new GetCountOrdersForUserUsingHEADParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCountOrdersForUserUsingHEADParamsWithContext(ctx context.Context) *GetCountOrdersForUserUsingHEADParams {
	var ()
	return &GetCountOrdersForUserUsingHEADParams{

		Context: ctx,
	}
}

// NewGetCountOrdersForUserUsingHEADParamsWithHTTPClient creates a new GetCountOrdersForUserUsingHEADParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCountOrdersForUserUsingHEADParamsWithHTTPClient(client *http.Client) *GetCountOrdersForUserUsingHEADParams {
	var ()
	return &GetCountOrdersForUserUsingHEADParams{
		HTTPClient: client,
	}
}

/*GetCountOrdersForUserUsingHEADParams contains all the parameters to send to the API endpoint
for the get count orders for user using h e a d operation typically these are written to a http.Request
*/
type GetCountOrdersForUserUsingHEADParams struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*Statuses
	  Filters only certain order statuses. For example, statuses=CANCELLED,CHECKED_VALID would only return orders with status CANCELLED or CHECKED_VALID.

	*/
	Statuses *string
	/*UserID
	  User identifier or one of the literals : 'current' for currently authenticated user, 'anonymous' for anonymous user

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) WithTimeout(timeout time.Duration) *GetCountOrdersForUserUsingHEADParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) WithContext(ctx context.Context) *GetCountOrdersForUserUsingHEADParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) WithHTTPClient(client *http.Client) *GetCountOrdersForUserUsingHEADParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) WithBaseSiteID(baseSiteID string) *GetCountOrdersForUserUsingHEADParams {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithStatuses adds the statuses to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) WithStatuses(statuses *string) *GetCountOrdersForUserUsingHEADParams {
	o.SetStatuses(statuses)
	return o
}

// SetStatuses adds the statuses to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) SetStatuses(statuses *string) {
	o.Statuses = statuses
}

// WithUserID adds the userID to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) WithUserID(userID string) *GetCountOrdersForUserUsingHEADParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get count orders for user using h e a d params
func (o *GetCountOrdersForUserUsingHEADParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCountOrdersForUserUsingHEADParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	if o.Statuses != nil {

		// query param statuses
		var qrStatuses string
		if o.Statuses != nil {
			qrStatuses = *o.Statuses
		}
		qStatuses := qrStatuses
		if qStatuses != "" {
			if err := r.SetQueryParam("statuses", qStatuses); err != nil {
				return err
			}
		}

	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
