// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetOrderForUserByCodeUsingGETParams creates a new GetOrderForUserByCodeUsingGETParams object
// with the default values initialized.
func NewGetOrderForUserByCodeUsingGETParams() *GetOrderForUserByCodeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetOrderForUserByCodeUsingGETParams{
		Fields: &fieldsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrderForUserByCodeUsingGETParamsWithTimeout creates a new GetOrderForUserByCodeUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrderForUserByCodeUsingGETParamsWithTimeout(timeout time.Duration) *GetOrderForUserByCodeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetOrderForUserByCodeUsingGETParams{
		Fields: &fieldsDefault,

		timeout: timeout,
	}
}

// NewGetOrderForUserByCodeUsingGETParamsWithContext creates a new GetOrderForUserByCodeUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrderForUserByCodeUsingGETParamsWithContext(ctx context.Context) *GetOrderForUserByCodeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetOrderForUserByCodeUsingGETParams{
		Fields: &fieldsDefault,

		Context: ctx,
	}
}

// NewGetOrderForUserByCodeUsingGETParamsWithHTTPClient creates a new GetOrderForUserByCodeUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrderForUserByCodeUsingGETParamsWithHTTPClient(client *http.Client) *GetOrderForUserByCodeUsingGETParams {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &GetOrderForUserByCodeUsingGETParams{
		Fields:     &fieldsDefault,
		HTTPClient: client,
	}
}

/*GetOrderForUserByCodeUsingGETParams contains all the parameters to send to the API endpoint
for the get order for user by code using g e t operation typically these are written to a http.Request
*/
type GetOrderForUserByCodeUsingGETParams struct {

	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*Code
	  Order GUID (Globally Unique Identifier) or order CODE

	*/
	Code string
	/*Fields
	  Response configuration. This is the list of fields that should be returned in the response body.

	*/
	Fields *string
	/*UserID
	  User identifier or one of the literals : 'current' for currently authenticated user, 'anonymous' for anonymous user

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithTimeout(timeout time.Duration) *GetOrderForUserByCodeUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithContext(ctx context.Context) *GetOrderForUserByCodeUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithHTTPClient(client *http.Client) *GetOrderForUserByCodeUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSiteID adds the baseSiteID to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithBaseSiteID(baseSiteID string) *GetOrderForUserByCodeUsingGETParams {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithCode adds the code to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithCode(code string) *GetOrderForUserByCodeUsingGETParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetCode(code string) {
	o.Code = code
}

// WithFields adds the fields to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithFields(fields *string) *GetOrderForUserByCodeUsingGETParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserID adds the userID to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) WithUserID(userID string) *GetOrderForUserByCodeUsingGETParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get order for user by code using g e t params
func (o *GetOrderForUserByCodeUsingGETParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrderForUserByCodeUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	// path param code
	if err := r.SetPathParam("code", o.Code); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
