// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/gopdf/models"
	"golang.org/x/net/context"
)

// NewCreateAddressUsingPOST1Params creates a new CreateAddressUsingPOST1Params object
// with the default values initialized.
func NewCreateAddressUsingPOST1Params() *CreateAddressUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateAddressUsingPOST1Params{
		Fields: &fieldsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAddressUsingPOST1ParamsWithTimeout creates a new CreateAddressUsingPOST1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAddressUsingPOST1ParamsWithTimeout(timeout time.Duration) *CreateAddressUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateAddressUsingPOST1Params{
		Fields: &fieldsDefault,

		timeout: timeout,
	}
}

// NewCreateAddressUsingPOST1ParamsWithContext creates a new CreateAddressUsingPOST1Params object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAddressUsingPOST1ParamsWithContext(ctx context.Context) *CreateAddressUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateAddressUsingPOST1Params{
		Fields: &fieldsDefault,

		Context: ctx,
	}
}

// NewCreateAddressUsingPOST1ParamsWithHTTPClient creates a new CreateAddressUsingPOST1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAddressUsingPOST1ParamsWithHTTPClient(client *http.Client) *CreateAddressUsingPOST1Params {
	var (
		fieldsDefault = string("DEFAULT")
	)
	return &CreateAddressUsingPOST1Params{
		Fields:     &fieldsDefault,
		HTTPClient: client,
	}
}

/*CreateAddressUsingPOST1Params contains all the parameters to send to the API endpoint
for the create address using p o s t 1 operation typically these are written to a http.Request
*/
type CreateAddressUsingPOST1Params struct {

	/*Address
	  Address object.

	*/
	Address *models.AddressWsDTO
	/*BaseSiteID
	  Base site identifier

	*/
	BaseSiteID string
	/*Fields
	  Response configuration. This is the list of fields that should be returned in the response body.

	*/
	Fields *string
	/*UserID
	  User identifier or one of the literals : 'current' for currently authenticated user, 'anonymous' for anonymous user

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithTimeout(timeout time.Duration) *CreateAddressUsingPOST1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithContext(ctx context.Context) *CreateAddressUsingPOST1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithHTTPClient(client *http.Client) *CreateAddressUsingPOST1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithAddress(address *models.AddressWsDTO) *CreateAddressUsingPOST1Params {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetAddress(address *models.AddressWsDTO) {
	o.Address = address
}

// WithBaseSiteID adds the baseSiteID to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithBaseSiteID(baseSiteID string) *CreateAddressUsingPOST1Params {
	o.SetBaseSiteID(baseSiteID)
	return o
}

// SetBaseSiteID adds the baseSiteId to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetBaseSiteID(baseSiteID string) {
	o.BaseSiteID = baseSiteID
}

// WithFields adds the fields to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithFields(fields *string) *CreateAddressUsingPOST1Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserID adds the userID to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) WithUserID(userID string) *CreateAddressUsingPOST1Params {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the create address using p o s t 1 params
func (o *CreateAddressUsingPOST1Params) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAddressUsingPOST1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Address != nil {
		if err := r.SetBodyParam(o.Address); err != nil {
			return err
		}
	}

	// path param baseSiteId
	if err := r.SetPathParam("baseSiteId", o.BaseSiteID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
