// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAddressUsingDELETEReader is a Reader for the DeleteAddressUsingDELETE structure.
type DeleteAddressUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAddressUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAddressUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteAddressUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAddressUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAddressUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAddressUsingDELETEOK creates a DeleteAddressUsingDELETEOK with default headers values
func NewDeleteAddressUsingDELETEOK() *DeleteAddressUsingDELETEOK {
	return &DeleteAddressUsingDELETEOK{}
}

/*DeleteAddressUsingDELETEOK handles this case with default header values.

OK
*/
type DeleteAddressUsingDELETEOK struct {
}

func (o *DeleteAddressUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/addresses/{addressId}][%d] deleteAddressUsingDELETEOK ", 200)
}

func (o *DeleteAddressUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAddressUsingDELETENoContent creates a DeleteAddressUsingDELETENoContent with default headers values
func NewDeleteAddressUsingDELETENoContent() *DeleteAddressUsingDELETENoContent {
	return &DeleteAddressUsingDELETENoContent{}
}

/*DeleteAddressUsingDELETENoContent handles this case with default header values.

No Content
*/
type DeleteAddressUsingDELETENoContent struct {
}

func (o *DeleteAddressUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/addresses/{addressId}][%d] deleteAddressUsingDELETENoContent ", 204)
}

func (o *DeleteAddressUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAddressUsingDELETEUnauthorized creates a DeleteAddressUsingDELETEUnauthorized with default headers values
func NewDeleteAddressUsingDELETEUnauthorized() *DeleteAddressUsingDELETEUnauthorized {
	return &DeleteAddressUsingDELETEUnauthorized{}
}

/*DeleteAddressUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAddressUsingDELETEUnauthorized struct {
}

func (o *DeleteAddressUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/addresses/{addressId}][%d] deleteAddressUsingDELETEUnauthorized ", 401)
}

func (o *DeleteAddressUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAddressUsingDELETEForbidden creates a DeleteAddressUsingDELETEForbidden with default headers values
func NewDeleteAddressUsingDELETEForbidden() *DeleteAddressUsingDELETEForbidden {
	return &DeleteAddressUsingDELETEForbidden{}
}

/*DeleteAddressUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type DeleteAddressUsingDELETEForbidden struct {
}

func (o *DeleteAddressUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /{baseSiteId}/users/{userId}/addresses/{addressId}][%d] deleteAddressUsingDELETEForbidden ", 403)
}

func (o *DeleteAddressUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
