// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CardTypeListWsDTO card type list ws d t o
// swagger:model CardTypeListWsDTO
type CardTypeListWsDTO struct {

	// card types
	CardTypes []*CardTypeWsDTO `json:"cardTypes"`
}

// Validate validates this card type list ws d t o
func (m *CardTypeListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCardTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CardTypeListWsDTO) validateCardTypes(formats strfmt.Registry) error {

	if swag.IsZero(m.CardTypes) { // not required
		return nil
	}

	for i := 0; i < len(m.CardTypes); i++ {
		if swag.IsZero(m.CardTypes[i]) { // not required
			continue
		}

		if m.CardTypes[i] != nil {
			if err := m.CardTypes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cardTypes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CardTypeListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CardTypeListWsDTO) UnmarshalBinary(b []byte) error {
	var res CardTypeListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
