// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CatalogListWsDTO catalog list ws d t o
// swagger:model CatalogListWsDTO
type CatalogListWsDTO struct {

	// catalogs
	Catalogs []*CatalogWsDTO `json:"catalogs"`
}

// Validate validates this catalog list ws d t o
func (m *CatalogListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCatalogs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CatalogListWsDTO) validateCatalogs(formats strfmt.Registry) error {

	if swag.IsZero(m.Catalogs) { // not required
		return nil
	}

	for i := 0; i < len(m.Catalogs); i++ {
		if swag.IsZero(m.Catalogs[i]) { // not required
			continue
		}

		if m.Catalogs[i] != nil {
			if err := m.Catalogs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("catalogs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CatalogListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CatalogListWsDTO) UnmarshalBinary(b []byte) error {
	var res CatalogListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
