// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConsentTemplateListWsDTO consent template list ws d t o
// swagger:model ConsentTemplateListWsDTO
type ConsentTemplateListWsDTO struct {

	// consent templates
	ConsentTemplates []*ConsentTemplateWsDTO `json:"consentTemplates"`
}

// Validate validates this consent template list ws d t o
func (m *ConsentTemplateListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsentTemplates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsentTemplateListWsDTO) validateConsentTemplates(formats strfmt.Registry) error {

	if swag.IsZero(m.ConsentTemplates) { // not required
		return nil
	}

	for i := 0; i < len(m.ConsentTemplates); i++ {
		if swag.IsZero(m.ConsentTemplates[i]) { // not required
			continue
		}

		if m.ConsentTemplates[i] != nil {
			if err := m.ConsentTemplates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("consentTemplates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConsentTemplateListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConsentTemplateListWsDTO) UnmarshalBinary(b []byte) error {
	var res ConsentTemplateListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
