// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeliveryOrderEntryGroupWsDTO delivery order entry group ws d t o
// swagger:model DeliveryOrderEntryGroupWsDTO
type DeliveryOrderEntryGroupWsDTO struct {

	// delivery address
	DeliveryAddress *AddressWsDTO `json:"deliveryAddress,omitempty"`

	// entries
	Entries []*OrderEntryWsDTO `json:"entries"`

	// quantity
	Quantity int64 `json:"quantity,omitempty"`

	// total price with tax
	TotalPriceWithTax *PriceWsDTO `json:"totalPriceWithTax,omitempty"`
}

// Validate validates this delivery order entry group ws d t o
func (m *DeliveryOrderEntryGroupWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeliveryAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalPriceWithTax(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeliveryOrderEntryGroupWsDTO) validateDeliveryAddress(formats strfmt.Registry) error {

	if swag.IsZero(m.DeliveryAddress) { // not required
		return nil
	}

	if m.DeliveryAddress != nil {
		if err := m.DeliveryAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deliveryAddress")
			}
			return err
		}
	}

	return nil
}

func (m *DeliveryOrderEntryGroupWsDTO) validateEntries(formats strfmt.Registry) error {

	if swag.IsZero(m.Entries) { // not required
		return nil
	}

	for i := 0; i < len(m.Entries); i++ {
		if swag.IsZero(m.Entries[i]) { // not required
			continue
		}

		if m.Entries[i] != nil {
			if err := m.Entries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeliveryOrderEntryGroupWsDTO) validateTotalPriceWithTax(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalPriceWithTax) { // not required
		return nil
	}

	if m.TotalPriceWithTax != nil {
		if err := m.TotalPriceWithTax.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("totalPriceWithTax")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeliveryOrderEntryGroupWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeliveryOrderEntryGroupWsDTO) UnmarshalBinary(b []byte) error {
	var res DeliveryOrderEntryGroupWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
