// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FeatureUnitWsDTO feature unit ws d t o
// swagger:model FeatureUnitWsDTO
type FeatureUnitWsDTO struct {

	// name
	Name string `json:"name,omitempty"`

	// symbol
	Symbol string `json:"symbol,omitempty"`

	// unit type
	UnitType string `json:"unitType,omitempty"`
}

// Validate validates this feature unit ws d t o
func (m *FeatureUnitWsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FeatureUnitWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FeatureUnitWsDTO) UnmarshalBinary(b []byte) error {
	var res FeatureUnitWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
