// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderWsDTO order ws d t o
// swagger:model OrderWsDTO
type OrderWsDTO struct {

	// applied order promotions
	AppliedOrderPromotions []*PromotionResultWsDTO `json:"appliedOrderPromotions"`

	// applied product promotions
	AppliedProductPromotions []*PromotionResultWsDTO `json:"appliedProductPromotions"`

	// applied vouchers
	AppliedVouchers []*VoucherWsDTO `json:"appliedVouchers"`

	// calculated
	Calculated bool `json:"calculated,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// consignments
	Consignments []*ConsignmentWsDTO `json:"consignments"`

	// created
	// Format: date-time
	Created CustomDateTime `json:"created,omitempty"`

	// delivery address
	DeliveryAddress *AddressWsDTO `json:"deliveryAddress,omitempty"`

	// delivery cost
	DeliveryCost *PriceWsDTO `json:"deliveryCost,omitempty"`

	// delivery items quantity
	DeliveryItemsQuantity int64 `json:"deliveryItemsQuantity,omitempty"`

	// delivery mode
	DeliveryMode *DeliveryModeWsDTO `json:"deliveryMode,omitempty"`

	// delivery order groups
	DeliveryOrderGroups []*DeliveryOrderEntryGroupWsDTO `json:"deliveryOrderGroups"`

	// delivery status
	DeliveryStatus string `json:"deliveryStatus,omitempty"`

	// delivery status display
	DeliveryStatusDisplay string `json:"deliveryStatusDisplay,omitempty"`

	// entries
	Entries []*OrderEntryWsDTO `json:"entries"`

	// guest customer
	GuestCustomer bool `json:"guestCustomer,omitempty"`

	// guid
	GUID string `json:"guid,omitempty"`

	// net
	Net bool `json:"net,omitempty"`

	// order discounts
	OrderDiscounts *PriceWsDTO `json:"orderDiscounts,omitempty"`

	// payment address
	PaymentAddress *AddressWsDTO `json:"paymentAddress,omitempty"`

	// payment info
	PaymentInfo *PaymentDetailsWsDTO `json:"paymentInfo,omitempty"`

	// pickup items quantity
	PickupItemsQuantity int64 `json:"pickupItemsQuantity,omitempty"`

	// pickup order groups
	PickupOrderGroups []*PickupOrderEntryGroupWsDTO `json:"pickupOrderGroups"`

	// product discounts
	ProductDiscounts *PriceWsDTO `json:"productDiscounts,omitempty"`

	// site
	Site string `json:"site,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// status display
	StatusDisplay string `json:"statusDisplay,omitempty"`

	// store
	Store string `json:"store,omitempty"`

	// sub total
	SubTotal *PriceWsDTO `json:"subTotal,omitempty"`

	// total discounts
	TotalDiscounts *PriceWsDTO `json:"totalDiscounts,omitempty"`

	// total items
	TotalItems int32 `json:"totalItems,omitempty"`

	// total price
	TotalPrice *PriceWsDTO `json:"totalPrice,omitempty"`

	// total price with tax
	TotalPriceWithTax *PriceWsDTO `json:"totalPriceWithTax,omitempty"`

	// total tax
	TotalTax *PriceWsDTO `json:"totalTax,omitempty"`

	// unconsigned entries
	UnconsignedEntries []*OrderEntryWsDTO `json:"unconsignedEntries"`

	// user
	User *PrincipalWsDTO `json:"user,omitempty"`
}

// Validate validates this order ws d t o
func (m *OrderWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppliedOrderPromotions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAppliedProductPromotions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAppliedVouchers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConsignments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeliveryAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeliveryCost(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeliveryMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeliveryOrderGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaymentAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaymentInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePickupOrderGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubTotal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalPriceWithTax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalTax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnconsignedEntries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderWsDTO) validateAppliedOrderPromotions(formats strfmt.Registry) error {

	if swag.IsZero(m.AppliedOrderPromotions) { // not required
		return nil
	}

	for i := 0; i < len(m.AppliedOrderPromotions); i++ {
		if swag.IsZero(m.AppliedOrderPromotions[i]) { // not required
			continue
		}

		if m.AppliedOrderPromotions[i] != nil {
			if err := m.AppliedOrderPromotions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("appliedOrderPromotions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateAppliedProductPromotions(formats strfmt.Registry) error {

	if swag.IsZero(m.AppliedProductPromotions) { // not required
		return nil
	}

	for i := 0; i < len(m.AppliedProductPromotions); i++ {
		if swag.IsZero(m.AppliedProductPromotions[i]) { // not required
			continue
		}

		if m.AppliedProductPromotions[i] != nil {
			if err := m.AppliedProductPromotions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("appliedProductPromotions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateAppliedVouchers(formats strfmt.Registry) error {

	if swag.IsZero(m.AppliedVouchers) { // not required
		return nil
	}

	for i := 0; i < len(m.AppliedVouchers); i++ {
		if swag.IsZero(m.AppliedVouchers[i]) { // not required
			continue
		}

		if m.AppliedVouchers[i] != nil {
			if err := m.AppliedVouchers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("appliedVouchers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateConsignments(formats strfmt.Registry) error {

	if swag.IsZero(m.Consignments) { // not required
		return nil
	}

	for i := 0; i < len(m.Consignments); i++ {
		if swag.IsZero(m.Consignments[i]) { // not required
			continue
		}

		if m.Consignments[i] != nil {
			if err := m.Consignments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("consignments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateCreated(formats strfmt.Registry) error {

	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OrderWsDTO) validateDeliveryAddress(formats strfmt.Registry) error {

	if swag.IsZero(m.DeliveryAddress) { // not required
		return nil
	}

	if m.DeliveryAddress != nil {
		if err := m.DeliveryAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deliveryAddress")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateDeliveryCost(formats strfmt.Registry) error {

	if swag.IsZero(m.DeliveryCost) { // not required
		return nil
	}

	if m.DeliveryCost != nil {
		if err := m.DeliveryCost.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deliveryCost")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateDeliveryMode(formats strfmt.Registry) error {

	if swag.IsZero(m.DeliveryMode) { // not required
		return nil
	}

	if m.DeliveryMode != nil {
		if err := m.DeliveryMode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deliveryMode")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateDeliveryOrderGroups(formats strfmt.Registry) error {

	if swag.IsZero(m.DeliveryOrderGroups) { // not required
		return nil
	}

	for i := 0; i < len(m.DeliveryOrderGroups); i++ {
		if swag.IsZero(m.DeliveryOrderGroups[i]) { // not required
			continue
		}

		if m.DeliveryOrderGroups[i] != nil {
			if err := m.DeliveryOrderGroups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deliveryOrderGroups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateEntries(formats strfmt.Registry) error {

	if swag.IsZero(m.Entries) { // not required
		return nil
	}

	for i := 0; i < len(m.Entries); i++ {
		if swag.IsZero(m.Entries[i]) { // not required
			continue
		}

		if m.Entries[i] != nil {
			if err := m.Entries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateOrderDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(m.OrderDiscounts) { // not required
		return nil
	}

	if m.OrderDiscounts != nil {
		if err := m.OrderDiscounts.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("orderDiscounts")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validatePaymentAddress(formats strfmt.Registry) error {

	if swag.IsZero(m.PaymentAddress) { // not required
		return nil
	}

	if m.PaymentAddress != nil {
		if err := m.PaymentAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paymentAddress")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validatePaymentInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.PaymentInfo) { // not required
		return nil
	}

	if m.PaymentInfo != nil {
		if err := m.PaymentInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paymentInfo")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validatePickupOrderGroups(formats strfmt.Registry) error {

	if swag.IsZero(m.PickupOrderGroups) { // not required
		return nil
	}

	for i := 0; i < len(m.PickupOrderGroups); i++ {
		if swag.IsZero(m.PickupOrderGroups[i]) { // not required
			continue
		}

		if m.PickupOrderGroups[i] != nil {
			if err := m.PickupOrderGroups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pickupOrderGroups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateProductDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(m.ProductDiscounts) { // not required
		return nil
	}

	if m.ProductDiscounts != nil {
		if err := m.ProductDiscounts.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("productDiscounts")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateSubTotal(formats strfmt.Registry) error {

	if swag.IsZero(m.SubTotal) { // not required
		return nil
	}

	if m.SubTotal != nil {
		if err := m.SubTotal.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subTotal")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateTotalDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalDiscounts) { // not required
		return nil
	}

	if m.TotalDiscounts != nil {
		if err := m.TotalDiscounts.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("totalDiscounts")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateTotalPrice(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalPrice) { // not required
		return nil
	}

	if m.TotalPrice != nil {
		if err := m.TotalPrice.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("totalPrice")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateTotalPriceWithTax(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalPriceWithTax) { // not required
		return nil
	}

	if m.TotalPriceWithTax != nil {
		if err := m.TotalPriceWithTax.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("totalPriceWithTax")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateTotalTax(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalTax) { // not required
		return nil
	}

	if m.TotalTax != nil {
		if err := m.TotalTax.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("totalTax")
			}
			return err
		}
	}

	return nil
}

func (m *OrderWsDTO) validateUnconsignedEntries(formats strfmt.Registry) error {

	if swag.IsZero(m.UnconsignedEntries) { // not required
		return nil
	}

	for i := 0; i < len(m.UnconsignedEntries); i++ {
		if swag.IsZero(m.UnconsignedEntries[i]) { // not required
			continue
		}

		if m.UnconsignedEntries[i] != nil {
			if err := m.UnconsignedEntries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("unconsignedEntries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrderWsDTO) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderWsDTO) UnmarshalBinary(b []byte) error {
	var res OrderWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
