// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderStatusUpdateElementListWsDTO order status update element list ws d t o
// swagger:model OrderStatusUpdateElementListWsDTO
type OrderStatusUpdateElementListWsDTO struct {

	// order status update elements
	OrderStatusUpdateElements []*OrderStatusUpdateElementWsDTO `json:"orderStatusUpdateElements"`
}

// Validate validates this order status update element list ws d t o
func (m *OrderStatusUpdateElementListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderStatusUpdateElements(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderStatusUpdateElementListWsDTO) validateOrderStatusUpdateElements(formats strfmt.Registry) error {

	if swag.IsZero(m.OrderStatusUpdateElements) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderStatusUpdateElements); i++ {
		if swag.IsZero(m.OrderStatusUpdateElements[i]) { // not required
			continue
		}

		if m.OrderStatusUpdateElements[i] != nil {
			if err := m.OrderStatusUpdateElements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderStatusUpdateElements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderStatusUpdateElementListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderStatusUpdateElementListWsDTO) UnmarshalBinary(b []byte) error {
	var res OrderStatusUpdateElementListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
