// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderStatusUpdateElementWsDTO order status update element ws d t o
// swagger:model OrderStatusUpdateElementWsDTO
type OrderStatusUpdateElementWsDTO struct {

	// base site Id
	BaseSiteID string `json:"baseSiteId,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this order status update element ws d t o
func (m *OrderStatusUpdateElementWsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderStatusUpdateElementWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderStatusUpdateElementWsDTO) UnmarshalBinary(b []byte) error {
	var res OrderStatusUpdateElementWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
