// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PackagingInfoWsDTO packaging info ws d t o
// swagger:model PackagingInfoWsDTO
type PackagingInfoWsDTO struct {

	// dimension unit
	DimensionUnit string `json:"dimensionUnit,omitempty"`

	// gross weight
	GrossWeight string `json:"grossWeight,omitempty"`

	// height
	Height string `json:"height,omitempty"`

	// insured value
	InsuredValue string `json:"insuredValue,omitempty"`

	// length
	Length string `json:"length,omitempty"`

	// weight unit
	WeightUnit string `json:"weightUnit,omitempty"`

	// width
	Width string `json:"width,omitempty"`
}

// Validate validates this packaging info ws d t o
func (m *PackagingInfoWsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PackagingInfoWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackagingInfoWsDTO) UnmarshalBinary(b []byte) error {
	var res PackagingInfoWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
