// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaginationWsDTO pagination ws d t o
// swagger:model PaginationWsDTO
type PaginationWsDTO struct {

	// current page
	CurrentPage int32 `json:"currentPage,omitempty"`

	// page size
	PageSize int32 `json:"pageSize,omitempty"`

	// sort
	Sort string `json:"sort,omitempty"`

	// total pages
	TotalPages int32 `json:"totalPages,omitempty"`

	// total results
	TotalResults int64 `json:"totalResults,omitempty"`
}

// Validate validates this pagination ws d t o
func (m *PaginationWsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaginationWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaginationWsDTO) UnmarshalBinary(b []byte) error {
	var res PaginationWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
