// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PointOfServiceListWsDTO point of service list ws d t o
// swagger:model PointOfServiceListWsDTO
type PointOfServiceListWsDTO struct {

	// point of services
	PointOfServices []*PointOfServiceWsDTO `json:"pointOfServices"`
}

// Validate validates this point of service list ws d t o
func (m *PointOfServiceListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePointOfServices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PointOfServiceListWsDTO) validatePointOfServices(formats strfmt.Registry) error {

	if swag.IsZero(m.PointOfServices) { // not required
		return nil
	}

	for i := 0; i < len(m.PointOfServices); i++ {
		if swag.IsZero(m.PointOfServices[i]) { // not required
			continue
		}

		if m.PointOfServices[i] != nil {
			if err := m.PointOfServices[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pointOfServices" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PointOfServiceListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PointOfServiceListWsDTO) UnmarshalBinary(b []byte) error {
	var res PointOfServiceListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
