// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductExpressUpdateElementListWsDTO product express update element list ws d t o
// swagger:model ProductExpressUpdateElementListWsDTO
type ProductExpressUpdateElementListWsDTO struct {

	// product express update elements
	ProductExpressUpdateElements []*ProductExpressUpdateElementWsDTO `json:"productExpressUpdateElements"`
}

// Validate validates this product express update element list ws d t o
func (m *ProductExpressUpdateElementListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProductExpressUpdateElements(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductExpressUpdateElementListWsDTO) validateProductExpressUpdateElements(formats strfmt.Registry) error {

	if swag.IsZero(m.ProductExpressUpdateElements) { // not required
		return nil
	}

	for i := 0; i < len(m.ProductExpressUpdateElements); i++ {
		if swag.IsZero(m.ProductExpressUpdateElements[i]) { // not required
			continue
		}

		if m.ProductExpressUpdateElements[i] != nil {
			if err := m.ProductExpressUpdateElements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("productExpressUpdateElements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductExpressUpdateElementListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductExpressUpdateElementListWsDTO) UnmarshalBinary(b []byte) error {
	var res ProductExpressUpdateElementListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
