// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StockWsDTO stock ws d t o
// swagger:model StockWsDTO
type StockWsDTO struct {

	// stock level
	StockLevel int64 `json:"stockLevel,omitempty"`

	// stock level status
	StockLevelStatus string `json:"stockLevelStatus,omitempty"`
}

// Validate validates this stock ws d t o
func (m *StockWsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StockWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StockWsDTO) UnmarshalBinary(b []byte) error {
	var res StockWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
