// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SuggestionListWsDTO suggestion list ws d t o
// swagger:model SuggestionListWsDTO
type SuggestionListWsDTO struct {

	// suggestions
	Suggestions []*SuggestionWsDTO `json:"suggestions"`
}

// Validate validates this suggestion list ws d t o
func (m *SuggestionListWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSuggestions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SuggestionListWsDTO) validateSuggestions(formats strfmt.Registry) error {

	if swag.IsZero(m.Suggestions) { // not required
		return nil
	}

	for i := 0; i < len(m.Suggestions); i++ {
		if swag.IsZero(m.Suggestions[i]) { // not required
			continue
		}

		if m.Suggestions[i] != nil {
			if err := m.Suggestions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("suggestions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SuggestionListWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SuggestionListWsDTO) UnmarshalBinary(b []byte) error {
	var res SuggestionListWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
