// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WeekdayOpeningDayWsDTO weekday opening day ws d t o
// swagger:model WeekdayOpeningDayWsDTO
type WeekdayOpeningDayWsDTO struct {

	// closed
	Closed bool `json:"closed,omitempty"`

	// closing time
	ClosingTime *TimeWsDTO `json:"closingTime,omitempty"`

	// opening time
	OpeningTime *TimeWsDTO `json:"openingTime,omitempty"`

	// week day
	WeekDay string `json:"weekDay,omitempty"`
}

// Validate validates this weekday opening day ws d t o
func (m *WeekdayOpeningDayWsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClosingTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpeningTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WeekdayOpeningDayWsDTO) validateClosingTime(formats strfmt.Registry) error {

	if swag.IsZero(m.ClosingTime) { // not required
		return nil
	}

	if m.ClosingTime != nil {
		if err := m.ClosingTime.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("closingTime")
			}
			return err
		}
	}

	return nil
}

func (m *WeekdayOpeningDayWsDTO) validateOpeningTime(formats strfmt.Registry) error {

	if swag.IsZero(m.OpeningTime) { // not required
		return nil
	}

	if m.OpeningTime != nil {
		if err := m.OpeningTime.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("openingTime")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WeekdayOpeningDayWsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WeekdayOpeningDayWsDTO) UnmarshalBinary(b []byte) error {
	var res WeekdayOpeningDayWsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
